version: "3.9"

networks:
  my-kotlin-server-network:
    driver: bridge

services:
  taskmasterserver:
    image: my-kotlin-server
    networks:
      - my-kotlin-server-network
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://book_server_db:5432/kotlin_server_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

  postgres:
    image: postgres:16.4
    networks:
      - my-kotlin-server-network
    container_name: book_server_db
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kotlin_server_db
    command: postgres -c log_statement=all
