spring:
  application:
    name: KotlinApp

  datasource:
    url: jdbc:postgresql://localhost:5431/kotlin_server_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
